export const SubMenu = [
  {
    title: 'SD-WAN',
    match: /#\/sdwan/,
    submenu: [{
      isDrop: false,
      title: '总览',
      innerSkip: true,
      main: /\/overview/,
      href: '/sdwan/overview'
    }, {
      isDrop: false,
      title: 'SD-WAN网络',
      innerSkip: true,
      main: /\/network/,
      href: '/sdwan/network'
    }, {
      isDrop: false,
      title: 'CPE管理',
      innerSkip: true,
      main: /\/cpe/,
      href: '/sdwan/cpe'
    }, {
      isDrop: false,
      title: '高可用HA组',
      innerSkip: true,
      main: /\/ha/,
      href: '/sdwan/ha'
    }, {
      isDrop: false,
      title: '报警监控',
      innerSkip: false,
      main: /\/alarm/,
      href: '/boss/alarm/#/alarm/resourceCpe'
    }, {
      isDrop: true,
      title: '管理员',
      innerSkip: true,
      collapseOn: false,
      main: /\/(stock|vpe|linkMonitor|publicNetworkMonitor|vpeInterface|agentVersion|ceModel|ryuMonitor)/,
      submenu: [{
        title: 'CPE库存管理',
        innerSkip: true,
        href: '/sdwan/stock'
      }, {
        title: 'VPE管理',
        innerSkip: true,
        href: '/sdwan/vpe'
      }, {
        title: 'VPE-PE链路监控',
        innerSkip: true,
        href: '/sdwan/linkMonitor'
      }, {
        title: 'VPE公网监控',
        innerSkip: true,
        href: '/sdwan/publicNetworkMonitor'
      }, {
        title: 'VPE-PE接口管理',
        innerSkip: true,
        href: '/sdwan/vpeInterface'
      }, {
        title: 'Agent版本管理',
        innerSkip: true,
        href: '/sdwan/agentVersion'
      }, {
        title: 'CPE型号管理',
        innerSkip: true,
        href: '/sdwan/ceModel'
      }, {
        title: 'RYU监控',
        innerSkip: true,
        href: '/sdwan/ryuMonitor'
      }]
    }]
  }
  ];
